<a href="https://colab.research.google.com/github/YeonJaeHong/ESAA_homeworks/blob/main/9_22_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

파이썬 머신러닝 (118-145)

05.데이터 전처리

데이터 전처리는 ML 알고리즘만큼 중요. 사이킷런의 ML 알고리즘을 적용하기 전 데이터에 대해 미리 처리해야할 기본 사항
>> 결손값: NaN,NULL 값은 허용되지 않음->NULL 값은 고정된 다른 값으로 변환해야함
*   feature 값들중 null값이 얼마 안되면 피처의 평균값으로 대체 가능 그러나 null 이 대부분이면 해당 피처는 드롭하는 것이 좋음
*   가장 결정이 힘든 부분, null 값이 일정수준 존재 -> 평균으로 대체 했을때 왜곡이 심할때 정밀한 대체 값 선정

>> 사이킷런의 머신러닝 알고지름은 문자열 값을 입력값으로 허용안함


*   문자열 값을 인코딩 해서 숫자형으로 변환필요
*   문자열 피처는 카테고리형과 텍스트형피처 의미  (각각을 코드값, 벡터화 기법 사용)







데이터 인코딩
> 머신러닝을 위한 대표적인 인코딩 방법: Label encoding, OneHotencoding 두가지
>> 레이블 인코딩


*   카테고리 피처를 코드형 숫자로 변경 ('01'같은 코드 역시 문자열이므로 '1'로 바꿔야함)


*   LabelEncoder 클래스로 구현한다. LabelEncoder를 객체로 생성한후 fit()과 transform()을 호출해 레이블 인코딩을 수행




In [10]:
from sklearn.preprocessing import LabelEncoder
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','믹서','믹서']
#LabelEncoder를 객체로 생성한후 fit()과 transform() 으로 레이블 인코딩 수행
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩 변환값:',labels)


인코딩 변환값: [0 1 4 5 3 2 2]


In [11]:
print('인코딩 클래스:',encoder.classes_)


인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [12]:
#classes_속성은 0번부터 순서대로 변환된 인코딩 값에 대한 원본값을 가지고 있다.
#invers_transform()을 통해 인코딩 된 값을 다시 디코딩 할 수 있다.
print('디코딩 원본값:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


레이블 인코딩은 간단하게 문자열 값을 숫자형 카테고리값으로 변환하는데, 레이블 인코딩이 일괄적인 숫자 값으로 변환이 되면서 몇몇 ML 알고리즘에는 이를 적용할 경우 예측 성능이 떨어지는 경우가 발생 할 수 있다.
> 즉, 숫자의 크고 작음이 가중치를 부여할 수 있기에
>> 이러한 레이블 인코딩의 문제점을 해결하기 위한 인코딩 방식이 ONE-HOT Encoding

ONE-HOT Encoding
> 피처값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼엔 0을 표시하는 방식.
> 행 형태로 돼있는 피처의 고유 값을 열 형태로 차원을 변환한뒤, 고윳값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시

In [13]:
#해당 고유 값에 매칭되는 피처만 1이 되고 나머지는 0을 입력하며, 이러한 특성으로 원-핫 (여러개중 하나만 1)인코딩으로 명명하게 됨
#onehotencoder로 변환하기전 모든 문자열값은 숫자형으로 변환해야하고, 입력값으로 2차원 데이터가 필요하다
#onehotencoder을 이용해 데이터 변경

from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','믹서','믹서']

#먼저 숫자값으로 변환을 위해 labelencoder로 변환한다
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)

#2차원 데이터로 변환한다
labels=labels.reshape(-1,1)

#원핫인코딩
oh_encoder=OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)


원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(7, 6)


판다스에는 원-핫 인코딩을 더 쉽게 지원하는 api 존재. get_dummies()를 이용하면 된다
사이킷런의 onehotencoder과는 다르게 문자열 카테고리 값을 숫자형으로 변환할 필요 없이 바로 변환가능



In [14]:
import pandas as pd
df=pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

피처 스케일링과 정규화
> 표준화: 데이터의 피러 각각이 평균이0, 분산이 1 인 가우시안 정규 분포를 가진 값으로 변환하는 것 의미-> 개별 데이터의 크기를 모두 똑같은 단위로 변경하는
> StandardScaler: 서포트 벡터 머신, 선형회귀, 로지스틱 회귀는 데이터가 가우시안 분포를 가지고 있다고 가정되고 구현-> 사전에 표준화를 적용하는것


In [19]:
from sklearn.datasets import load_iris
import pandas as pd
#붓꽃 데이터 세트를 로딩하고 dataframe 으로 변환한다

iris=load_iris()
iris_data= iris.data
iris_df= pd.DataFrame(data=iris_data,columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\feature들의 분산 값')
print(iris_df.var())


feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
eature들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [20]:
# standardscaler를 이용해 각 피처를 한번에 표준화해 변환한다.
# transform()을 호출할떼 스케일 변환된 데이터 세트가 넘파이의 ndarray이므로 이를 dataframe으로 변환해 평군값과 분산 값을 다시 확인해보자

from sklearn.preprocessing import StandardScaler

#StandardScaler 객체 생성
scaler=StandardScaler()
#StandardScaler로 데이터 세트 변환.fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

#transform() 시 스케일 변환된 데이터 세트가 numpy ndarray로 반환돼 이를 dataframe으로 변환
iris_df_scaled= pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('feature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


MinMaxSclaer
> 데이터값을 0과 1사이의 범위 값으로 변환


In [21]:
from sklearn.preprocessing import MinMaxScaler

#MinMaxScaler 객체 생성
scaler=MinMaxScaler()
#StandardScaler로 데이터 세트 변환.fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

#transform() 시 스케일 변환된 데이터 세트가 Numpy ndarray로 반환돼 이를 dataframe으로 변환
iris_df_scaled= pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
print('feature 들의 최솟값')
print(iris_df_scaled.min())
print('feature 들의 최댓값')
print(iris_df_scaled.max())

feature 들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature 들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


테스트 데이터에 fit()을 호출하지 않고 학습 데이터로 fit()을 수행한 MinMaxScaler객체의 tranform()을 이용해 데이터를 변환한다.
>결과물이 테스트 데이터가 모두 동일하게 1/10로 변환되었음을 알 수 있다


In [23]:
train_array= np.arange(0,11).reshape(-1,1)
test_array=np.arange(0,6).reshape(-1,1)

scaler=MinMaxScaler()
scaler.fit(train_array)
train_scaled=scaler.transform(train_array)
print('원본 train_array 데이터:', np.round(train_array.reshape(-1),2))
print('Scale된 train_array 데이터:',np.round(train_scaled.reshape(-1),2))

#test_array에 scale 변환을 할떄는 반드시 fit()을 호출하지 않고 transform()만으로만 변환해야함
test_scaled = scaler.transform(test_array)
print('원본 train_array 데이터:', np.round(train_array.reshape(-1),2))
print('Scale된 train_array 데이터:',np.round(train_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


학습데이터와 테스트 데이터의 fit(), transform()을 이용해 스케일링 변환시 유의할점
> 가능하다면 전체 데이터의 스케일링 변환을 적용한 뒤 학습과 테스트 데이터로 분리
> 학습 데이터로 이미 fit()된 scaler 객체를 이용해 transform()으로 변