<a href="https://colab.research.google.com/github/YeonJaeHong/ESAA_homeworks/blob/main/9_22_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

02. 사이킷런으로 시작하는 머신러닝
> 2-1. 사이킷런 소개와 특징



사이킷런은 파이썬 머신러닝 라이브러리중 가장 많이 사용되는 라이브러리.
파이썬 기반의 머신러닝은 곧 사이킷런으로 개발하는 것을 의미할 정도로 오랜 기간 파이썬 세계에서 인정받았다.
> 02. 첫번째 머신러닝 만들어보기- 불꽃 품종 예측하기
* 분류: 대표적인 지도학습 방법의 하나
* 사이킷런 매키지 내의모듈명은 sklearn으로 시작하는 명명규칙이 있다.
* 하이퍼 파라미터 : 머신러닝 알고리즘별로 최적의 학습을 위해 직접 입력하는 파라미터를 통칭
* 데이터 세트를 학습 데이터와 테스트 데이터로 분리하는데는 train_test_split() 함수를 사용

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


In [ ]:
#iris 데이터들의 feature 들과 data값이 어떻게 구성되어있는지 알기위해 dataframe으로 변환
import pandas as pd

#붗꽃 데이터 세트를 로딩
iris= load_iris()

#iris.data는 Iris 데이터 세트에서 feature로만된 데이터를 numpy로 가지고 있다
iris_data=iris.data

#iris.target은 불꽃 데이터 세트에서 레이블(결정값) 데이터를 numpy로 가지고 있다
iris_label= iris.target
print('iris target값:',iris_label)
print('iris target명:', iris.target_names)

#붓꽃 데이터 세트를 자세히 보기 위해 dataframe으로 변환
iris_df= pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']= iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [ ]:
X_train,X_test,y_train,y_test= train_test_split(iris_data, iris_label,test_size=0.2, random_state=11)
#학습용 데이터와 테스트용 데이터를 분리하기
# 학습데이터로 학습된 모델이 얼마나 뛰어난 성능을 가지는지 평가하기 위해 테스트 데이터세트가 필요함 -> train_test_split() API 제공
# train_test_split() ; 학습 데이터와 테스트 데이터를 test_size 파라미터 입력 값을 비율로 분할. test_size=0.2로 입력 파라미터 설정하면 전체 데이터중 테스트 데이터가 20%,학습데이커가 80%으로 데이터를 분할



In [ ]:
#DecisionTreeClassifier 객체 생성
dt_clf= DecisionTreeClassifier(random_state=11)
#학습수행
dt_clf.fit(X_train,y_train)
# 이제 결정 트리 기반의 DecisionTreeClassifier 객체는 학습 데이터를 기반으로 학습이 완료했고 이렇게 학습된 decisionTreeClassifier 객체를 이용해 예측 수행
# decisiontreeclassifier 객체의 predict() 메서드에 테스트용 피처 데이터 세트를 입력해 호출하면 학습된 모델 기반에서 테스트 데이터 세트에 대한 예측값을 반환


DecisionTreeClassifier(random_state=11)

In [ ]:
#학습이 완료된 decisiontreeclassifier 객체에서 테스트 데이터 세트로 예측 수행
pred=dt_clf.predict(X_test)

In [ ]:
#예측결과를 기반으로 의사결정 트리 기반의 decisiontreeclassifier 예측성능 평가하기-> 정확도 사용
#정확도: 예측결과 값이 실제 리이블 값과 얼마나 정확하게 맞는지를 평가하는 지표; accuracy_score() 함수 제공
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.933333


1. 데이터 세트 분리: 데이터를 학습데이터와 테스트 데이터로 분리
2. 모델 학습: 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델 학습
3. 예측수행: 학습된 ML모델을 이용해 테스트 데이터의 분류(붓꽃 종류)를 예측
4. 평가: 이렇게 예측된 결괏값과 테스트 데이터의 실제 결괏값을 비교해 ML 모델 성능 평가


03. 사이킷런 기반 프레임워크 익히기
> ESTIMATOR 이해 및 fit(), predic() method
* 사이킷런은 api 일관성과 개발 편의성을 제공하기 위한 노력이 엿보이는 패키지
* 사이킷런은 ML 모델 학습을 위해서 fit()을, 학습된 모델의 예측을 위해 predic() 메서드를 제공
* 지도학습의 주요 두 축의 분류(classification)과 회귀(regression)의 다양한 알고리즘을 구현한 모든 사이킷런 클래스는 fit()과 predict()만을 이용해 간단하게 학습과 예측결과를 반환
*분류알고리즘을 구현한 클래스를 classifier로, 회귀알고리즘을 구현한 클래스를 regressor로 지칭.
*사이킷런이 제공하는 많은 유형의 classifier과 regressor 클래스를 합쳐스 estimator 클래스라고 부름-> 지도학습의 모든 알고리즘을 구현한 클래스: estimator이라고 부름

*cross_al_Score()와 같은 evalution함수, GridSearchCV와 같은 하이퍼 파라미터 튜닝을 지원하는 클래스의 경우 이 Estimator을 인자로 받는다
* 인자로 받은 estimato에 대해서 cross_val_score(), GRIDsEARCHcv.fit()함수 내에서 Estimator의 fit()과 predict()를 호출해서 평가를 하거나 하이퍼 파라미터 튜닝을 수행하는 것


In [ ]:
#fit. transform, fit_transform()

사이킷런의 주 모듈
예제 데이터:  sklearn.datasets :사이킷런에 내장되어 예제로 제공되는 데이터세트,
피처 처리: sklearn.preprocessing : 데이터 전처리에 필요한 다양한 가공 기능 제공(문자열을 숫자형 코드값으로 인코딩, 정규화, 스케일링 등)
sklearn.feature_selection: 알고리즘에 큰영향을 미치는 피처를 우선순위대로 셀력션 작업을 수행하는 다양한 기능 제공
sklearn.feature_extraction:  텍스트 데이터나 이미지 데이터의 벡터화된 피처를 추출하는데 사용됨
피처처리,차원 축소: sklearn.decomposition
데이터 분리, 검증, 파라미터 튜닝: sklearn.model_selection
평가: sklearn.metrics
> 일반적으로 머신러닝 모델을 구축하는 주요 프로세스는 피처의 가공, 변경, 추출을 수행하는 피처 처리, ml 알고리즘 학습/예측 수행, 모델 평가의 단계를 반복적으로 수행하는것. 사이킷런 패키지는 머신러닝 모델을 구축하는 프로세스를 지원하기 위해 매우 편리하고 다양하며 유연한 모듈을 지원.
> 내장된 예제 데이터 세트 -> 이 데이터는  datasets 모듈에 있는 여러 api를 호출해 만들수 있다.
> fetch 계열의 명령은 데이터 크기가 커서 패키지에 저장돼 있지 않고 인터넷에서 내려받아 홈 디렉처리 아래의 sicikit_learn_data 라는 서브 디렉토리에 저장한후 춯루 불러들이는 데이터
>분류와 클러스터링을 위한 표본 데이터 생성기
: datasets.make_classifications(): 분류를 위한 데이터세틍를 만든다. 특히 높은 상관도, 불필요한 속성등의 노이즈 효과를 위한 데이터를 무작위로 생성
: datasets.make_blobs() : 클러스터링을 위한 데이터 세트를 무작위로 생성해준다. 군집 지정 개수에 따라 여러가지 클러스터링을 위한 데이터세트를 쉽게 만들어준다
> 분류나 회귀를 위한 연습용 예제 데이터에 대해 알아보기: 주로 딕셔너리 형태로 존재

* data: 피처의 데이터세트를 가르킨다.
* target: 분류시 레이블, 회귀일떄는 숫자결괏값 데이터세트
* target_names 일때는 개별 레이블의 이름을 나타낸다
* feature_names: 피처의 이름
* data, target은 넘파이 타입이고, target_names,feature_names은 넘파이 또는 파이썬 리스트 타입이다.
* 피처의 데이터값을 반환받기 위해서는 내장 데이터 세트 API를 호출한 뒤에 그 KEY 값을 지정하면 된다.


In [ ]:
#붓꽃 데이터세트 생성
from sklearn.datasets import load_iris
iris_data= load_iris()
print(type(iris_data))


<class 'sklearn.utils._bunch.Bunch'>


In [ ]:
keys=iris_data.keys()
print('붓꽃 데이터 세트의 키들:',keys)


붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print('/n feature_name의 type:',type(iris_data.feature_names))
print('feature_names의 shape:',len(iris_data.feature_names))
print(iris_data.feature_names)
print('/n target_names의 type:',type(iris_data.target_names))
print('target_names의 shape:',len(iris_data.target_names))

/n feature_name의 type: <class 'list'>
feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
/n target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: 3


In [ ]:
print(iris_data.target_names)
print('\n data의 type:',type(iris_data.data))
print('data의 shape:',iris_data.data.shape)
print(iris_data['data'])

print('\n target 의 type:', type(iris_data.target))
print('target 의 shape:', iris_data.target.shape)
print(iris_data.target)

['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1

04. Model selection 모듈 소개
> 사이킷런의 model_selection 모듈은 학습 데이터와 테스트 데이터 세트를 분리하거나 교차 검증 분할 및 평가, 그리고 estimator의 하이퍼 파라미터를 튜닝하기 위한 다양한 함수와 클래스를 제공한다. 전체 데이터를 학습 데이터와 테스트 데이터 세트로 분리해주는 train_test_split() 을 살펴본다

In [ ]:
#학습/테스트 데이터 세트 분리 - train_test_split()
# 테스트 데이터 세트를 이용하기 않고 학습 데이터 세트로만 학습하고 예측하면 발생하는 문제
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris= load_iris()
dt_clf= DecisionTreeClassifier()
train_data= iris.data
train_label= iris.target
dt_clf.fit(train_data, train_label)

#학습 데이터 세트으로 예측 수행
pred= dt_clf.predict(train_data)
print('예측 정확도:', accuracy_score(train_label, pred))


예측 정확도: 1.0


In [ ]:
#위는 학습 데이터를 기반으로 예측했기 때문에 정확도가 100%인 이상한 결과가 나온다.
#예측을 수행하는 데이터 세트는 학습을 수행한 학습용 데이터 세트가 아닌 전용 테스트 데이터 세트여야함.
#train_test_split() 을 이용해 붓꽃 데이터 세트를 학습 및 테스트 데이터 세트로 분리할 수 있음
#train_test_split() 첫번째 파라미터로 피처 데이터 세트, 두번째로 레이블 데이트 세트를 입력받음
#test_size: 전체 데이터에서 테스트 데이터 세트 크기를 얼마로 샘플링할것인지를 결정
#shuffle: 데이터를 분리하기 전 데이터를 미리 섞을지를 결정 디폴트 값은 true
#random_state:  random_state는 호출할때마다 동일한 학습/테스트용 데이터세트를 생성하기 위해 주어지는 난수값. 수행할때마다 동일한 데이터 세트로 분리하기 위해서는 random_State를 일정한 값으로 부여


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
dt_clf= DecisionTreeClassifier()
iris_data= load_iris()
X_train,X_test,y_train,y_test= train_test_split(iris_data.data, iris_data.target,test_size=0.3,random_state=121)


In [ ]:
dt_clf.fit(X_train,y_train)
pred=dt_clf.predict(X_test)
print('예측 정확도: {0:4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.955556


교차 검증

별도의 테스트용 데이터가 필요하다고 말함
과적합에 취약한 약점을 가질 수 있다
해당 테스트 데이터에만 과적합 되는 학습 모델이 만들어져 다른 테스트용 데이터가 들어올 경우에는 성능이 저하된다-> 교차검증을 하는 이유 (데이터 편증을 막기위해)
>#대부분의 ML 모델의 성능 평가는 교차 검증 기반으로 1차 평가를 한뒤에 최종적으로 테스트 데이터세트에 적용해 평가하는 프로세스
>#ML에 사용되는 데이터 세트를 세분화해서 학습, 검증, 테스트 데이터 세트로 나누 수 있다.

k 폴드 교차 검증
> 가장 보편적으로 사용되는 교차 검증 기법. K개의 데이터 폴드 세트를 만들어서 K번만큼 각 폴트 세트에 학습과 검정 평가를 반복적으로 수행하는 방법
>데이터를 K 등분 한 다음 첫번째 반복에서 검증데이터 세트 하나를 제외하고 나머지를 학습데이터 세트에 넣은 다음 , 학습 데이터 세트에서 학습을 수행하고 검증 데이터세트에서 평가를 수행한다. 이 과정을 K 등분한것들 순서를 바꾸어서(?) 마지막 K번째까지 수행을 한 다음 학습과 검증을 수행하는 것이 K 폴드 교차 검증이다.


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris=load_iris()
features= iris.data
label=iris.target
dt_clf= DecisionTreeClassifier(random_state=156)

#5개의 폴드세트로 분리하는 kFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold= KFold(n_splits=5)
cv_accuracy=[]
print('붓꽃 데이터 세트 크기:',features.shape[0])


붓꽃 데이터 세트 크기: 150


In [ ]:
#KFold(n_splits=5)로 Fold 객체를 생성했으므로 이제 생성된 KFold 객체의 split()을 호출해서 전체 붓꽃 데이터를 5개의 폴드 데이터 세트로 분리한다.
#다음 코드는 폴드 세트를 생성하는 KFold 객체의 split()을 호출해 교차 검증 수행시마다 학습과 검증을 반복해 예측 정확도를 측정
n_iter=0
#KFold 객체의 split()를 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
  #kfold.split() 으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test= features[train_index],features[test_index]
  y_train, y_test=label[train_index],label[test_index]
  #학습및 예측
  dt_clf.fit(X_train,y_train)
  ped=dt_clf.predict(X_test)
  n_iter+=1
  #반복 시마다 정확도 측정
  accuracy= np.round(accuracy_score(y_test,pred),4)
  train_size= X_train.shape[0]
  test_size=X_test.shape[0]
  print('\n#{0} 교차 검증 정확도:{1}, 학습 데이터 크기:{2}, 검증 데이터크기:{3}'.format(n_iter,accuracy,train_size,test_size))
  print('#{0} 검증 세트 인덱스:{1}',format(n_iter,test_index))
  cv_accuracy.append(accuracy)
  #개별 iteration별 정홛로를 합하여 평균 정확도 계산
  print('\n## 평균 검증 정확도:',np.mean(cv_accuracy))

ValueError: ignored

In [ ]:
#stratified K 폴드
#불균형한 분포도를 가진 레이블 데이터 집합을 위한 k 폴드 방식으로, 값의 분포가 한쪽으로 치우치는 데이터를 이용해야 할때 사용된다.
#k 폴드가 레이블 데이터 집이 원본 데이터 집합의 레이블 분호를 학습 및 테스트 세트에 제대로 분배하지 못하는 경우의 문제를 해결한다
import pandas as pd
iris= load_iris()
iris_df= pd.DataFrame(data=iris.data, columns= iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()


0    50
1    50
2    50
Name: label, dtype: int64

In [ ]:
#3개의 품종이 모두 50개로 값이 동일. 그래서 3개의 폴드세트를 kfold 로 생성하고 각 교차 검증시마다 생성되는 학습/검증 레이블 데이터값의 분포도를 확인
kfold=KFold(n_splits=3)
n_iter=0
for train_index,test_index in kfold.split(iris_df):
  n_iter+=1
  label_train=iris_df['label'].iloc[train_index]
  label_test=iris_df['label'].iloc[test_index]
  print('##교차검증:{0}'.format(n_iter))
  print('학습 레이블 데이터 분포:',label_train.value_counts())
  print('검증 레이블 데이터 분포:',label_test.value_counts())iris_df['label'].value_counts()


SyntaxError: ignored

>교차 검증시 마다 3개의 폴드 세트로 만들어지는 학습레이블과 검증 레이블이 완전히 다른 값으로 추출
> 그렇기에 학습레이블은 1,2 밖에 없고 검증 레이블은 0 밖에 없으므로 학습모델은 검사 정확도가 0이 될 수 밖에 없다