**머신러닝**
> 지도학습, 비지도 학습, 강화학습으로 분류
>>지도학습은 분류와 회귀로 나누어짐
> 사이킷런의 머신러닝 알고리즘에 입력하기 위한 데이터의 추출,가공,변형은 넘파이와 판다스를 주로 이용

**넘파이**
>넘파이의 특징:
>> numpy의 기본 데이터 타입은 ndarray 이고, 이를 이용해 다차원배열 생성,수행가능

In [1]:
import numpy as np # numpy 모듈을 import

In [2]:
array1= np.array([1,2,3]) # array() 함수는 인자를 입력받아 ndarray로 변환
print ('array1 type:', type(array1))
print ('array1 array 형태:', array1.shape) #shape 변수는 ndarry 의 크기를 나타냄

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [3]:
array2= np.array([[1,2,3],
                 [2,3,4]])
print ('array2 type:', type(array2))
print ('array2 array 형태:', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [4]:
array3= np.array([[1,2,3]])
print ('array3 type:', type(array3))
print ('array3 array 형태:', array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


ndarray.shape : ndarray의 차원과 크기를 tuple로 나타낸다.
>여기서 array1 과 array3은 동일한 데이터건수를 가지지만, shape는 (3,0) 과 (1,3) 으로 다른것을 확인 가능하다.
>>array1: 1차원 array로 3개 데이터를 가진다는 뜻 (3,0)
>>array3: 2차원 데이터로 1개row, 3개 column 을 가진다는 뜻 (1,3)

-> 각 array의 차원을 ndarray.ndim을 이용해 확인가능

In [5]:
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1:1차원, array2:2차원, array3: 2차원


In [6]:
list1= [1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype) #list1의 자료형은 integer인 숫자를 가지고 있음

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [7]:
list2=[1,2,'test']  #int, string 이섞임
array2=np.array(list2)
print(array2,array2.dtype) # int와 string이 섞인 list2->ndarray로 변환하면 숫자형 1,2 모두 문자형으로 변환

list3=[1,2,3.0] # int와 float가 섞임
array3=np.array(list3)
print(array3,array3.dtype) #동일하게 list3이 int1,2가 float 1,2로 변함

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [8]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64') #int 32-> float64로 변경
print(array_float,array_float.dtype)

array_int1 = array_float.astype('int32') #다시 float64 -> int32 로 변경



print(array_int1,array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])  #float -> int로 변경하면 소숫점 없어진다!
array_int2 = array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [9]:
sequence_array= np.arange(10) # np.arange -> array를 range()로 표현
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [10]:
zero_array = np.zeros((3,2),dtype='int32')  # zero() -> 함수 인자로 튜플형태의 shape 값 입력하면 모든 값이 0인 shape의 ndarray 생성
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array = np.ones((3,2))  # ones() -> zero()에서 0이 아닌 1
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


reshape() -> ndarray의 차원과 크기 변경

In [11]:
array1 =np.arange(10)
print('array1:',array1)

array2 = array1.reshape(2,5)
print('array2:',array2)

array3 = array1.reshape(5,2)
print('array3:',array3)

array1: [0 1 2 3 4 5 6 7 8 9]
array2: [[0 1 2 3 4]
 [5 6 7 8 9]]
array3: [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array1.reshape(4,3) 같은 경우는 error가 발생 (변경이 안되는 사이즈)

In [12]:
array1 =np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)  # row= -1, column= 5 ; array1와 호환될수 있는 column이 5개인 2차원ndarray로 변환해라 -> 그래서 2x5 shape
print('array2 shape:', array2.shape)

array3 = array1.reshape(5,-1) # array1와 호환될수 있는 row가 5개인 2차원ndarray로 변환해라 -> 그래서 5x2 shape
print('array3 shape:', array3.shape)

#reshape (-1,4)는 error발생!

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [13]:
array1 = np.arange(8)
array3d= array1.reshape((2,2,2))
print('array3d:',array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:',array5.tolist())
print('array5 shape:',array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:',array6.tolist())
print('array6 shape:',array6.shape)


array3d: [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5: [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6: [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


reshape(-1,1) -> 원본 ndarray의 형태과 관계없이 반드시 column이 1개인 2차원으로 변환
tolist() -> ndarray를 list 자료형으로 변환 (보기 용이함)

**Indexing**

indexing : numpy 에서 ndarray 내의 일부 데이터세트 또는 특정 데이터만 선택할 수 있게함
  1) 특정데이터 추출 : 원하는 위치의 인덱스 값 지정
  2) slicing : 연속된 인덱스상의 ndarray 출력하는 방법 ':' 기호 사이 시작,종료 인덱스를 표시하면 시작인덱스->종료인덱스-1 위치의 데이터의 ndarray 반환
  3) fancy indexing : 일정한 인덱싱 집합을 list, ndarray형태로 지정해 위치의 데이터 반환
  4) boolean indexing:  조건에 해당하는 여부인 true/false 값 인덱싱을 기반, true에 해당하는 위치에 있는 데이터의 ndarray 반환

  * 인덱스 -1은 맨뒤의 데이터값을 의미, -2는 맨뒤에서 두번째값 의미

In [15]:
#단일값 추출
# 1 ~9까지 1차원
array1= np.arange(start=1,stop=10)
print('array1:',array1)
#index는 0부터 시작, array1[2]-> 3번째 index 위치의 데이터값 의미
value=array1[2]
print('value:',value)
print(type(value))

# 인덱스 -1은 맨뒤의 데이터값을 의미, -2는 맨뒤에서 두번째값 의미
print(array1[-1], array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
9 8


In [16]:
# 단일 인덱스를 이용해 ndarray 내의 데이터값 수정
array1[0] =9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [17]:
array1d= np.arange(start=1, stop=10)
array2d= array1d.reshape(3,3) # 3x3
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0])
print('(row=0,col=1) index 가리키는 값:', array2d[0,1])
print('(row=1,col=0) index 가리키는 값:', array2d[1,0])
print('(row=2,col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


axis 0 :row 방향 축
axis 1 : column 방향 축

In [18]:
#slicing
array1= np.arange(start=1, stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

#slicing 규칙
# 1) : 기호앞에 시작인덱스를 생략하면 자동으로 맨처음인덱스인 0으로 간주
# 2) : 기호 뒤에 종료인텍스 생략하면 자동으로 맨 마지막 인덱스로 간주
# 3) : 기호 앞/뒤에 시작/종료 인덱스를 생락하면 자동으로 맨처음/마지막 인덱스로 간주

[1 2 3]
<class 'numpy.ndarray'>


In [19]:
array1= np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)

array5=array1[:3]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[1 2 3]
[1 2 3 4 5 6 7 8 9]


In [20]:
array1d= np.arange(start=1, stop=10)
array2d= array1d.reshape(3,3) # 3x3
print(array2d)

print('array2d[0:2,0:2]:', array2d[0:2,0:2])
print('array2d[1:3,0:3]:', array2d[1:3,0:3])
print('array2d[1:3,:]:', array2d[1:3,:])
print('array2d[:,:]:', array2d[:,:])
print('array2d[:2,0:]:', array2d[:2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]: [[1 2]
 [4 5]]
array2d[1:3,0:3]: [[4 5 6]
 [7 8 9]]
array2d[1:3,:]: [[4 5 6]
 [7 8 9]]
array2d[:,:]: [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,0:]: [1 4]


In [21]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [23]:
# fancy indexing
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)

array3= array2d[[0,1],2]   # axis0 에는 fancyindexing ,axis1에는 단일값인덱싱
print('array2d[[0,1],2]->',array3.tolist())

array4= array2d[[0,1],0:2]
print('array2d[[0,1],0:2]->', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]]->', array5.tolist())



array2d[[0,1],2]-> [3, 6]
array2d[[0,1],0:2]-> [[1, 2], [4, 5]]
array2d[[0,1]]-> [[1, 2, 3], [4, 5, 6]]


In [25]:
#boolean indexing : 조건 필터링과 검색을 동시에 할 수 있음
array1d= np.arange(start=1, stop=10)
#[] 안에 array1d > 5 Boolean indexing을 적용 ; 데이터값이 5보다 큰 데이터만 추출
array3 = array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)


array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [26]:
array1d>5 # 반환값을 보면, 5보다큰 값은 True, 작은 값은 False가 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [27]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3= array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:',array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [28]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:',array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


In [30]:
boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])
array3= array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)


불린 인덱스로 필터링 결과: [6 7 8 9]


In [31]:
# 위의 boolean 코드와 결과 동일
indexes = np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:',array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


**행렬의 정렬-sort(), argsort()**

In [34]:
#np.sort()  넘파이에서 sort()를 호출하는 방식. ndarrary.sort() 같이 행렬자체에서 sort()를 호출하는 방식

org_array = np.array([3,1,9,5])
print('원본 행렬:',org_array)

#np.sort()로 정렬
sort_array1= np.sort(org_array)
print ('np.sort()호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort()호출후 원본 행렬:',org_array)

#ndarray.sort() 로 정렬
sort_array2= org_array.sort()
print('org_array.sort()호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

#정리: [3,1,9,5] 원본 행렬에 대해
# np.sort() -> 정렬된 형태로 반환 / ndarray.sort() -> 원본 행렬 자체를 정렬후 변환


원본 행렬: [3 1 9 5]
np.sort()호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort()호출후 원본 행렬: [3 1 9 5]
org_array.sort()호출 후 반환된 행렬: None
org_array.sort() 호출 후 반환된 행렬: [1 3 5 9]


In [39]:
sort_array1_desc = np.sort(org_array)[::-1] #내림차순으로 정렬하려면 np.sort()[::-1] 사용
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [42]:
#2차원 이상의 행렬의 경우 axis 축 값 설정으로 통해 row, column 방향으로 정렬 수행 가능
array2d = np.array([[8,12],
                  [7,1]])
sort_array2d_axis0= np.sort(array2d,axis=0)
print('로우 방향으로 정렬:', sort_array2d_axis0)

sort_array2d_axis1= np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬:', sort_array2d_axis1)


로우 방향으로 정렬: [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬: [[ 8 12]
 [ 1  7]]


**정렬된 행렬의 인덱스 반환하기**
-> 원본 행렬이 정렬된후 기존 원본행렬의 원소에 대한 인덱스를 얻을때:
np.argsort() 사용. (정렬행렬의 원본 행렬 인덱스를 반환)

In [43]:
org_array=np.array([3,1,9,5])
sort_indices= np.argsort(org_array)  # [3,1,9,5]의 정렬 된 행렬의 원본 행렬 인덱스는 [1,0,3,2]
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
org_array=np.array([3,1,9,5])
sort_indices_desc= np.argsort(org_array)[::-1]  # 내림차순으로 정렬시에 원본 행렬 인덱스를 구하는 방법 [::-1] 이용
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

In [44]:
name_array= np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc= np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])


성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


**선형대수 연산- 행렬 내적과 전치 행렬 구하기**


> 내적: dot 함수
> 전치행렬: transpose()




In [45]:
A= np.array([[1,2,3,],[4,5,6,]])
B= np.array([[7,8],[9,10],[11,12]])
dot_product= np.dot(A,B)
print('행렬내적결과: ', dot_product)

행렬내적결과:  [[ 58  64]
 [139 154]]


In [46]:
A= np.array([[1,2],[3,4]])
transpose_mat= np.transpose(A)
print('A의 전치 행렬:', transpose_mat)

A의 전치 행렬: [[1 3]
 [2 4]]
