<a href="https://colab.research.google.com/github/YeonJaeHong/ESAA_homeworks/blob/main/Numpy_exercises.9.8ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.version)
print(np.show_config())

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    li

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
a=np.zeros(10)
print(a.size)

10


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a= np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
a= np.arange(start=10,stop=50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
a=np.arange(10)
b=a[::-1]
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
a=np.arange(9)
a=a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
a= np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [13]:
a= np.identity(3)
a
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [16]:
a=np.random.random((3,3,3))
a

array([[[0.31477935, 0.57514715, 0.19979269],
        [0.3011919 , 0.3068355 , 0.40769113],
        [0.71758239, 0.08384657, 0.61285119]],

       [[0.86708999, 0.93360703, 0.63468305],
        [0.57313884, 0.79875762, 0.76591272],
        [0.1139246 , 0.17193028, 0.26516388]],

       [[0.89878229, 0.88798854, 0.30838343],
        [0.42479915, 0.79385012, 0.57662104],
        [0.55471382, 0.0420698 , 0.05231308]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [19]:
a=np.random.random((10,10))
print(a.min())
print(a.max())


0.006951849400058663
0.9918361396602158


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [20]:
array = np.random.random(30)
print(array.mean())

0.48208344836931016


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
x= np.ones([5,5])
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array1d= np.arange(1,10)
a= array1d[3<array1d]
b= a[a<8]
print(b)

[4 5 6 7]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [23]:
import numpy as np
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
z3= np.intersect1d(Z1,Z2)
print(z3)

[5 7 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [24]:
import numpy as np
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-24-62fa731a8227>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [25]:
Z = np.arange('2016-07','2016-08',
              dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [26]:
A = np.ones(3)*1
B = np.ones(3)*2
((A+B)*(-A/2))

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [28]:
a= np.random.random(10)
B = np.random.random(10)*10
B = B - B%1
B


array([8., 4., 1., 4., 5., 2., 5., 0., 1., 9.])

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [29]:
Z = np.random.randint(0,4,25).reshape(5,5)
print(Z)

[[0 1 0 0 0]
 [0 0 3 3 1]
 [1 0 2 1 2]
 [1 2 1 0 2]
 [0 0 1 0 0]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [32]:
a= np.random.randint(1,10,10)
b=np.sort(a)
print(b)

[2 3 3 3 4 4 5 8 8 9]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [33]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [34]:
A=np.random.random((10,2))
print(A)
X,Y = A[:,0], A[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)
array = np.array(R)
R = array.reshape(10,1)
array1 = np.array(T)
T = array1.reshape(10,1)
arr = np.concatenate([R, T], axis=1)
arr

[[0.40161426 0.33473572]
 [0.08062962 0.41486842]
 [0.88195912 0.3097829 ]
 [0.1595784  0.96416382]
 [0.9981587  0.58691854]
 [0.73569677 0.56589463]
 [0.63661511 0.72494796]
 [0.43036257 0.62950024]
 [0.71965002 0.26971799]
 [0.92755822 0.66152347]]
[0.52282121 0.42263097 0.93478197 0.97728048 1.15792667 0.92816296
 0.96479446 0.76254999 0.76853363 1.13928818]
[0.69482228 1.37883945 0.33778268 1.40677362 0.53155015 0.65567345
 0.85018344 0.97112289 0.35858699 0.6195223 ]


array([[0.52282121, 0.69482228],
       [0.42263097, 1.37883945],
       [0.93478197, 0.33778268],
       [0.97728048, 1.40677362],
       [1.15792667, 0.53155015],
       [0.92816296, 0.65567345],
       [0.96479446, 0.85018344],
       [0.76254999, 0.97112289],
       [0.76853363, 0.35858699],
       [1.13928818, 0.6195223 ]])

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [35]:
z = np.random.random(10)
print(z)
print(max(z))
z[z.argmax()] = 0
print(max(z))

[0.2672896  0.94767925 0.07955628 0.63793158 0.63087582 0.59636297
 0.2647647  0.86948514 0.55977795 0.11419928]
0.9476792536610347
0.8694851449445888


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [39]:
Z = np.arange(100)
v = np.random.uniform(0,100)
x=(Z-v)*(Z-v)
x=np.square(x)
print(x.argmin())
print(v)
Z[x.argmin()]

93
92.58399379966416


93

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [40]:
n = 3
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),4)
print(Z)

[[0. 0. 4.]
 [0. 0. 4.]
 [0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [41]:
# column 1
Z = np.random.randint(0,10,(3,3))
k= Z[:,0]
b=np.sort(k)
print(b)


[0 3 7]


In [42]:
# column 2
print(Z)
print(Z[Z[:, 1].argsort()])

[[0 8 1]
 [3 9 1]
 [7 5 5]]
[[7 5 5]
 [0 8 1]
 [3 9 1]]


In [43]:
# column 3
print(Z)
print(Z[Z[:, 2].argsort()])

[[0 8 1]
 [3 9 1]
 [7 5 5]]
[[0 8 1]
 [3 9 1]
 [7 5 5]]
